Create Pak-Je-Kans.md
EneroMangal4321/mijn-amsterdam-stagair pull request #6
Opened 2020-04-03 10:39 UTC by EneroMangal4321

Review Pak-Je-Kans.md

2020-04-07 12:50 UTC, timvanoostrom requested changes
Hoi Enero, het schrijven van documenten (bv een story) is belangrijk en geen makkelijke maar wel een heel handige skill. Code moet ook netjes, duidelijk en betekenisvol geschreven worden. 

Verplaats jezelf in een potentiële lezer van dit document (een collega, een stagebegeleider, klasgenoot of leraar). Jezelf wat kritische vragen stellen over de inhoud van het document en afvragen of deze vragen beantwoord worden is een goede manier om na te gaan of het document goed genoeg is.

Bv: Hoe bepaal je of voorzieningen voor iemand van toepasing zijn? Hoe lees je die gegevens in en stuur je deze naar de front-end? Hoe zien die voorzieningen files eruit? Welke gegevens staan erin? Over wat voor voorwaarden hebben het precies?

Ik stel voor dat je eea nog wat duidelijker uiteenzet en laat reviewen voordat we deze story als gesloten kunnen beschouwen.

2020-04-07 12:50 UTC, timvanoostrom commented on Pak-Je-Kans.md
> +We willen een plek maken op Mijn Amsterdam genaamd Pak Je Kans voorzieningencheck, hier kunnen mensen zien waar ze recht op hebben. Deze armoedevoorzieningen worden zo persoonlijk mogelijk gefilterd.
... `hier kunnen mensen zien waar ze recht op hebben.` ... Misschien kun je hier al wat specifieker zijn, het gaat om `voorzieningen voor mensen met een laag inkomen` Het woord `armoedevoorziening` kun je beter niet gebruiken.

...`als de burger toegeeft dat we zijn of haar egevens gebruiken`... moet zijn ...`als de burger toestemming geeft om zijn of haar gegevens te mogen gebruiken`...

`Het doel van deze omgeving is ervoor zorgen dat de burger beter zicht heeft op wat ze allemaal recht hebben. ` Deze zin is niet zo mooi, kun je die herschrijven?

`De burgers kunnen het ook direct aanvragen.` Wanneer en hoe?

2020-04-07 12:50 UTC, timvanoostrom commented on Pak-Je-Kans.md
> +
Als we 3 bovenstaande puntjes hebben uitgevoerd, hebben we dan een werkende back-end?

2020-04-07 12:50 UTC, timvanoostrom commented on Pak-Je-Kans.md
> +---
Denk aan: briefing, ontwerp, contactpersonen, ux onderzoek etc.

2020-04-07 12:50 UTC, timvanoostrom commented on Pak-Je-Kans.md
> +* design : Bram
Begin elk puntje met een hoofdletter.

2020-04-07 12:50 UTC, timvanoostrom commented on Pak-Je-Kans.md
> +    2. wat moet waar komen
Meestal zijn er nog wat feedbackrondes, tekstuele redactie en uitwerking in Invision

2020-04-07 12:50 UTC, timvanoostrom commented on Pak-Je-Kans.md
> +    1. uit verschillende databases persoonlijke gegevens ophalen van andere instellingen.
Als de voorzieningencheck werkt met de rule engine, is dit dan van toepassing?

2020-04-07 12:50 UTC, timvanoostrom commented on Pak-Je-Kans.md
> +    2. de juiste gegevens ophalen uit de database.
Is dit niet hetzelfde als puntje 1?

2020-04-07 12:50 UTC, timvanoostrom commented on Pak-Je-Kans.md
> +    1. welke informatie moet je doorgeven.
doorgeven waaraan?

2020-04-10 08:40 UTC, timvanoostrom requested changes

2020-04-10 08:40 UTC, timvanoostrom commented on Pak-Je-Kans.md
> +    2. Hat moet waar komen
Typo!

2020-04-10 08:40 UTC, timvanoostrom commented on Pak-Je-Kans.md
> +    1. Hoe gaat het er uit zien
Verzamelen en organiseren van data voor rules, bepalen van voorwaarden zodat de rules gefilterd kunnen worden

2020-04-10 08:40 UTC, timvanoostrom commented on Pak-Je-Kans.md
> +
We hebben oa ook nog nodig:
- Netwerkconnectiviteit + bijbehorende env variabelen om connectie te maken met de bron api
- Achter TMA plaatsen
- Certificaten
- Jenkinsfile voor build en deploy
- Kibana en Sentry logging views op de NUC

Kun je dit verder nog bij @drakonen verifiëren?

2020-04-10 08:40 UTC, timvanoostrom commented on Pak-Je-Kans.md
> +---
Het gaat over een projectbeschrijving. Het is dus een totaaloverzicht (in dit geval met meer nadruk op back-end).

2020-04-10 08:40 UTC, timvanoostrom commented on Pak-Je-Kans.md
> +* design : Bram
`D`esign

2020-04-15 15:57 UTC, timvanoostrom approved these changes
Ik vind het goed. Mooi dat je jezelf er ook bij hebt gezet :-)

2020-04-17 10:23 UTC, drakonen commented on .gitignore
> +*.docx
Ik denk dat je alleen de laatste nodig hebt. `*.docx` omvat ook `Pak-Je-Kans.docx`
`.docx/` is voor een directory genaamt `.docx`. Die heb je niet denk ik?

Het is het beste om dit netjes en minimaal te houden, om verwarring in de toekomst te vermijden.

2020-04-17 10:23 UTC, drakonen commented on Pak-Je-Kans.md
> +In dit bestand ga ik uitleggen wat er gemaakt moet worden. Ook ga ik beschrijven wat dit betekend voor de back end. Ik zal ook de benodigdheden zoals informatie en tools die handig zijn noemen en bes
Persoonlijke Inkomens Omgeving (PIO)
Wat is PIO? Toevallig weet ik het nu, maar over een jaar misschien niet meer. 1 keer de afkorting voluit schrijven kan daarbij helpen bij de absolute wildgroei aan drie letterige afkortingen (DLA) bij de gemeente.

2020-04-17 10:23 UTC, drakonen commented on Pak-Je-Kans.md
> +    4. Flask (Is een framework voor Python)
```suggestion
    4. Flask (Is een web-framework voor Python)
```

2020-04-21 12:24 UTC, merged